import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer | CVForge",
  description:
    "Disclaimer for CVForge, an AI resume builder by Tezsid Designs Pvt Ltd.",
};

const sections = [
  {
    title: "General Information",
    points: [
      "CVForge is an AI-assisted resume builder provided by Tezsid Designs Pvt Ltd to help users create, improve, and tailor resume content.",
      "The content generated by CVForge is for general guidance and resume drafting support only.",
      "Users are responsible for reviewing, editing, and verifying all resume details before using, submitting, or sharing the final resume.",
    ],
  },
  {
    title: "No Job Guarantee",
    points: [
      "CVForge does not guarantee interview calls, job placement, hiring decisions, salary outcomes, or acceptance by any employer, recruiter, ATS platform, or institution.",
      "Resume quality is only one part of a job application. Hiring outcomes may depend on skills, experience, market demand, interview performance, employer requirements, and other factors outside our control.",
    ],
  },
  {
    title: "AI-Generated Content",
    points: [
      "CVForge may use AI systems to analyze user inputs and generate resume suggestions, summaries, bullet points, and role-specific content.",
      "AI-generated content may occasionally be incomplete, inaccurate, repetitive, or unsuitable for a specific role.",
      "Users must not include false, misleading, exaggerated, confidential, or unauthorized information in their resume.",
    ],
  },
  {
    title: "Accuracy Of User Information",
    points: [
      "Users are solely responsible for the accuracy of personal details, education, work experience, projects, skills, achievements, links, and contact information entered into CVForge.",
      "Tezsid Designs Pvt Ltd is not responsible for any loss, rejection, dispute, or consequence arising from incorrect or misleading information provided by a user.",
    ],
  },
  {
    title: "Third-Party Platforms",
    points: [
      "CVForge may help prepare content for use on job portals, company career pages, LinkedIn, GitHub, or other third-party platforms.",
      "We do not control third-party platforms, their ATS systems, hiring criteria, privacy practices, availability, or terms of use.",
    ],
  },
  {
    title: "Limitation Of Liability",
    points: [
      "To the fullest extent permitted by applicable law, Tezsid Designs Pvt Ltd will not be liable for direct, indirect, incidental, consequential, or special damages arising from the use of CVForge.",
      "Use of CVForge is at the user's own discretion and risk.",
    ],
  },
];

export default function DisclaimerPage(): React.JSX.Element {
  return (
    <main className="relative min-h-screen overflow-hidden bg-[#0a0a0a] px-6 py-14 text-zinc-100 sm:px-10">
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute -top-24 left-1/2 h-80 w-80 -translate-x-1/2 rounded-full bg-violet-500/20 blur-3xl" />
        <div className="absolute bottom-0 right-0 h-72 w-72 rounded-full bg-indigo-500/10 blur-3xl" />
      </div>

      <section className="relative z-10 mx-auto max-w-4xl animate-fade-in-up">
        <Link
          href="/"
          className="mb-8 inline-flex text-sm font-medium text-violet-200 transition hover:text-white"
        >
         &larr; Back to home
        </Link>

        <div className="rounded-3xl border border-white/10 bg-zinc-900/60 p-6 shadow-2xl shadow-black/20 backdrop-blur-sm sm:p-10">
          <p className="text-sm font-medium uppercase tracking-[0.2em] text-violet-200">
            Published: May 20, 2026
          </p>
          <h1 className="mt-3 text-3xl font-bold tracking-tight text-white sm:text-5xl">
            Disclaimer
          </h1>
          <p className="mt-5 text-base leading-7 text-zinc-300">
            This Disclaimer applies to CVForge, an AI Resume Builder owned and
            operated by Tezsid Designs Pvt Ltd. By using this website or its
            resume-building features, you agree to the points below.
          </p>

          <div className="mt-10 space-y-8">
            {sections.map((section) => (
              <section key={section.title}>
                <h2 className="text-xl font-semibold text-white">
                  {section.title}
                </h2>
                <ul className="mt-3 space-y-3 text-sm leading-6 text-zinc-300">
                  {section.points.map((point) => (
                    <li key={point} className="flex gap-3">
                      <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-violet-300" />
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>
              </section>
            ))}

            <section className="rounded-2xl border border-violet-400/20 bg-violet-500/10 p-5">
              <h2 className="text-xl font-semibold text-white">Contact</h2>
              <p className="mt-3 text-sm leading-6 text-zinc-300">
                For questions about this Disclaimer, contact Tezsid Designs Pvt
                Ltd at{" "}
                <a
                  href="mailto:info@tezsid.com"
                  className="font-medium text-violet-200 hover:text-white"
                >
                  info@tezsid.com
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </section>
    </main>
  );
}
